ellisonleao/gruvbox.nvim

lua/gruvbox.lua
Remove hardcoded background color for "Todo" and "Error" groups.
=> gruvbox-community/gruvbox/pull/149

lua/gruvbox/settings.lua
After switching to this plugin, I noticed that my tabline looked off, and I traced it to the inverse flag always being on. This fixes it by changing to the same scheme used by `invert_signs`
=> Fix tabline always being inverted

lua/gruvbox/settings.lua
Mispelled `contrast_light`, fixed.
=> Fix contrast_light typo

lua/gruvbox/plugins/highlights.lua
This highlight group is used for code lenses of the built-in lsp client.
Before:
Notice how the virtual text of the code lens (`int -> int`) looks like real text/code.
After:
=> highlight LspCodeLens like comments

lua/gruvbox/languages.lua
in the original gruvbox they would be in orange.
=> highlight rust documentation comments differently than normal comments

lua/gruvbox/base.lua, lua/gruvbox/plugins/highlights.lua
Fix: #71 
I think using Fg4 for Popupmenu selection color is better because `CmpItemAbbrMatch` is already blue.
Also I find really annoying bold yellow for `LspReference*`, wouldn't it better to softly highlight them as I've done in the commit?
=> Add nvim-cmp highlights + minor improvements

colors/gruvbox.vim
`lush` clears all defined highlight groups by default when applying, so any unknown to `gruvbox.nvim` plugins loaded after it will loose all their groups. Let's keep unknown highlight groups untouched - they probably have reasonable defaults.
=> Do not clear ALL highlight groups before applying gruvbox colors

lua/gruvbox/base.lua
Fix #80
Making delimiters gray wasn't a good idea
=> Fix delimiters color

lua/gruvbox/plugins/highlights.lua
This PR aims to properly solve the issue raised here: https://github.com/ellisonleao/gruvbox.nvim/pull/90
Searching through `nvim-treesitter` and reading the [docs](https://github.com/nvim-treesitter/nvim-treesitter/blob/d2174f1d29086b51124d084f9402c5f9731f21bd/doc/nvim-treesitter.txt#L510-L512) it's clear that it's recommended to not set `TSError` or set it to `Normal`.
Showing syntax and parser errors is rarely wanted, which is clearly proved by https://github.com/ellisonleao/gruvbox.nvim/pull/90.
Ref: https://github.com/nvim-treesitter/nvim-treesitter/pull/1628
=> fix: clear TSError highlight

lua/gruvbox/base.lua
There is already a bunch of possible configuration for other kind of color like `vim.g.gruvbox_sign_column` and `vim.g.gruvbox_number_column`.
This PR brings the same feature for the CursorLine to be able to create an homogeneous theme variation.
=> add support for vim.g.gruvbox_cursor_line

lua/gruvbox/base.lua
Hi @ellisonleao, thanks for your excellent port of my favorite colorscheme!
I noticed a minor annoyance and thought I'd open a PR. Essentially what happens when you do a project wide search (with ripgrep or whatever), I prefer only the search term to be highlighted (expected behavior). This does not happen currently.
Take a look at the before/after for a clearer example.
Before:
After:
=> Fix quickfix search highlighting

lua/gruvbox/base.lua
This PR links the new `CurSearch` highlight with the `IncSearch` highlight. This gives a consistent highlight of the first and current search.
See https://github.com/neovim/neovim/pull/18081 for more details.
=> fix: add cursearch highlight

lua/gruvbox/groups.lua
This PR repairs the `IncSearch` highlight. It previously used `hls_cursor` which is no longer defined. The correct value is `orange`.
=> fix: repair inc search fg

lua/gruvbox/groups.lua
neutral colors are missing for neovim terminal colors.
=> fix: neutral colors

lua/gruvbox/groups.lua
`colors.faded_blue` is nil, which was leading to `debugPC` not being highlighted.
=> fix: debugPC highlight

README.md, lua/gruvbox/groups.lua, lua/gruvbox/init.lua, tests/gruvbox/gruvbox_spec.lua
Added `palette_overrides` config key:
```lua
require("gruvbox").setup({
palette_overrides = {
bright_green = "#990000",
}
})
vim.cmd("colorscheme gruvbox")
```
It will fix: https://github.com/ellisonleao/gruvbox.nvim/issues/144
=> Add palette overriding

lua/gruvbox/groups.lua
Diff files are currently missing highlighting.
See https://github.com/nvim-treesitter/nvim-treesitter/commit/1e4b23c26678bd36e3da638183996eaa30e7fba8.
=> Add treesitter highlight groups for diff

lua/gruvbox/groups.lua
Add missing `CocMenuSel` group for coc.nvim, without this the completion menu had no colors. I chose `PmenuSel` because it seems appropriate, feel free to edit if there's a better match
=> Add missing highlight group for coc.nvim

lua/gruvbox/groups.lua
I think has a lot more sense making `Directory` gruvboxblue since is by default the colors of the directories in the terminal. Also I think we are using gruvboxblue for NvimTree directories too.
=> fix: make directories gruvboxblue

lua/gruvbox/init.lua
As of #163, NVIM's minimum required version was upgraded to 0.8. However, the related check at runtime was never updated. This PR has Gruvbox check the correct minimum required version of NVIM.
=> Fix nvim version check (0.7+ -> 0.8+)

lua/gruvbox/groups.lua
The split used to show the background color (left side).
Also changed `VertSplit` (deprecated) to `WinSeparator`.
=> fix transparent background on window seperator

lua/gruvbox/groups.lua
This PR adds NoiceCursor highlight group, fixes noice's cmdline cursor.
<details>
<summary>Old description</summary>
For some reason, `Cursor` reverse is set to `config.inverse` value.
If I change `config.inverse` cursor stays the same.
| `reverse` = true | `reverse` = false |
| ---------------- | ----------------- |
| ![rtrue]         | ![rfalse]         |
| ![rtrue2]        | ![rfalse2]        |
[rtrue]: https://i.imgur.com/sPVqwxd.png
[rtrue2]: https://i.imgur.com/iTPIIo8.png
[rfalse]: https://i.imgur.com/ITY7vfQ.png
[rfalse2]: https://i.imgur.com/d0k0iIP.png
**But**, if reverse is false, noice.nvim cmdline cursor breaks.
| `reverse` = true | `reverse` = false |
| ---------------- | ----------------- |
| ![ntrue]         | ![nfalse]         |
[nfalse]: https://i.imgur.com/jq0bGZr.png …
=> feat: add `NoiceCursor` highlight group

lua/gruvbox/groups.lua, lua/gruvbox/palette.lua, tests/gruvbox/gruvbox_spec.lua
Another attempt to fix the override logic. Seems like `link` and other configs should **not** live together. This PR is rolling back the old logic to simplify things
Ref #223
Reverting #207
=> fixing override logic

lua/gruvbox/groups.lua
With transparency set to `true` and without this group floats like Lazy, Mason, NvTerm etc look pretty ugly
And with it:
=> Add transparency to floats

lua/gruvbox/groups.lua
See https://github.com/neovim/neovim/pull/15018 for more information.
=> fix: add highlight for active parameter in signature help

lua/gruvbox/groups.lua
`bright_orange` should be `orange` when calling `colors` from `require("gruvbox.palette").get_base_colors(vim.o.background, config.contrast)`
fix #231
=> fix: LspSignatureActiveParameter color

lua/gruvbox/groups.lua
`Error` would inverse the color. That cause text with treesitter-error unreadable.
=> remove treesitter-error highlight link

lua/gruvbox/groups.lua
This improve special comment keywords.
Here is how it will look like:
=> fix(groups): Improve special comment keywords

lua/gruvbox/groups.lua
After last update of neovim + gruvbox, LSP sends document highlights once ready. While this is a great feature, it's a bit annoying with gruvbox, because color-groups are not consistent, which causes a lot changes in the colors, once LSP is loaded (after a few seconds). Furthermore, colors are a bit strange now (see https://github.com/ellisonleao/gruvbox.nvim/issues/237).
With the few changes in this PR, the behaviour is slightly improved IMO, at least in C++ and Rust: colors change less between LSP and treesitter, and feel more logical.
Details:
- @lsp.type.struct and @lsp.type.class are redirected to @type. Things reported as struct and class by LSP are "type" in Treesitter ( in C++ and Rust at least) so this removes a lot of color changes. And binding them to @constructor (redirected …
=> Proposal: make LspSemanticHighlight more consistent with Treesitter

lua/gruvbox/groups.lua
Hey, thanks for your work !
This PR adds support for the vim-illuminate plugin.
Link to the repo: https://github.com/RRethy/vim-illuminate
----------------------
May I suggest using a highlighted background instead of changing the text color ? Of course it always comes down to preferences, and I have my own override, but I feel like most people will prefer the "traditional" way of highlighting, it feels weird in code:
Maybe linking `LspReference*` to the `Visual` highlighting group would be more appropriate ?
Granted, it's less colorful, but it's much more readable in my opinion
=> Add support for vim-illuminate plugin

lua/gruvbox.lua
Without LSP semantic highlight:
With LSP semantic highlight (jdtls):
This PR defines a highlight for java modifiers linking to the appropriate treesitter highlight shown in the first screenshot.
=> Add @lsp.type.modifier.java

lua/gruvbox.lua
Added a highlight group that was missing:
before:
after:
=> Missing CocSearch highlight
