ellisonleao/gruvbox.nvim

- lua/gruvbox.lua
Refer to [gruvbox.vim (L378-L381)](https://github.com/gruvbox-community/gruvbox/blob/master/colors/gruvbox.vim#L378-L381).
> Fix hls_cursor -> hls_highlight

- README.md
> Fixed setting colorscheme in init.vim

- lua/gruvbox/base.lua
Light overrides was also overriding hard/soft bg
> fix hard/soft contrast with light background

- lua/gruvbox/base.lua
Lush has renamed a package. Seems to work locally, but would welcome additional testing. Thanks! :) 
closes #54
> Compatability with newer lush version

- colors/gruvbox.vim
Reverts ellisonleao/gruvbox.nvim#75
See my comment https://github.com/ellisonleao/gruvbox.nvim/pull/75#issuecomment-974866189
> Revert "Do not clear ALL highlight groups before applying gruvbox colors"

- lua/gruvbox/settings.lua
Same piece of code is repeated above.
> Removal of repeated code

- lua/gruvbox/plugins.lua
GitSignsChange was too similar with GitSignsAdd
fixes #106
> change GitSignsChange to orange

- lua/gruvbox/groups.lua
Added highlight groups for plugin: [dashboard](https://github.com/glepnir/dashboard-nvim)
> Add dashboard-nvim hlGroups

- lua/gruvbox/groups.lua
> feat: add groups for Mason

- lua/gruvbox/groups.lua
> feat: add nvim-tree colors based on exa style

- lua/gruvbox/groups.lua
https://github.com/lvimuser/lsp-inlayhints.nvim/blob/9bcd6fe25417b7808fe039ab63d4224f2071d24a/README.md#highlight
> Support lsp-inlayhints.nvim

- lua/gruvbox/groups.lua
Open for discussion :slightly_smiling_face:
Closes #162
> feat: add Winbar highlight groups

- lua/gruvbox/groups.lua
> chore: repair IncSearch linking for CurSearch

- lua/gruvbox/groups.lua
> Add Whitespace group

- lua/gruvbox/groups.lua
This will make listchars disappear!
Fixes #203
> Do not use the same color for Whitespace as for Cursorline

- lua/gruvbox/groups.lua
See https://github.com/rcarriga/nvim-notify#highlights for more information.
> feat: add notify nvim highlights

- lua/gruvbox/groups.lua
This adds support for lsp semantic highlight with neovim >= 0.9
Fixes #241
> feat: Add support for lsp semantic highlight

- lua/gruvbox/groups.lua
Add support for nvim-ts-rainbow2
> feat(groups): Add support for nvim-ts-rainbow2

- lua/gruvbox.lua
> feat: add EndOfBuffer highlight group

- lua/gruvbox.lua
original code
```vim
" Directory names, special names in listing
hi! link Directory GruvboxGreenBold
```
> fix Directory color according to the original code
